apiVersion: batch/v1
kind: Job
metadata:
  name: preferred-replica-election
  namespace: kafka
spec:
  template:
    metadata:
      name: preferred-replica-election
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:2.4.0@sha256:201a1c7fd378405b6b1bfd801127c8a530ed7a971282bfcee4ec731bc0c50ad2
        command:
        - ./bin/kafka-preferred-replica-election.sh
        - --zookeeper
        - zookeeper:2181
      restartPolicy: Never
  backoffLimit: 3
